// Dados oficiais da Copa do Mundo FIFA 2026 — horários de Brasília.
// Gerado em 11/06/2026. A tabela completa fica embutida: o app funciona
// mesmo sem internet; o placar ao vivo é uma camada extra via /api/placar.
const DADOS = {
 "jogos": [
  {
   "id": 1,
   "fase": "grupos",
   "grupo": "A",
   "num": null,
   "data": "2026-06-11",
   "diaSemana": "Quinta-feira",
   "hora": "16h00",
   "iso": "2026-06-11T16:00:00-03:00",
   "t1": "México",
   "t2": "África do Sul",
   "cidade": "Cidade do México",
   "estadio": "Estádio Azteca (Banorte)",
   "brasil": false,
   "p1": 2,
   "p2": 0,
   "fim": true
  },
  {
   "id": 2,
   "fase": "grupos",
   "grupo": "A",
   "num": null,
   "data": "2026-06-11",
   "diaSemana": "Quinta-feira",
   "hora": "23h00",
   "iso": "2026-06-11T23:00:00-03:00",
   "t1": "Coreia do Sul",
   "t2": "República Tcheca",
   "cidade": "Guadalajara",
   "estadio": "Estadio Akron",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 3,
   "fase": "grupos",
   "grupo": "B",
   "num": null,
   "data": "2026-06-12",
   "diaSemana": "Sexta-feira",
   "hora": "16h00",
   "iso": "2026-06-12T16:00:00-03:00",
   "t1": "Canadá",
   "t2": "Bósnia e Herzegovina",
   "cidade": "Toronto",
   "estadio": "BMO Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 4,
   "fase": "grupos",
   "grupo": "D",
   "num": null,
   "data": "2026-06-12",
   "diaSemana": "Sexta-feira",
   "hora": "22h00",
   "iso": "2026-06-12T22:00:00-03:00",
   "t1": "Estados Unidos",
   "t2": "Paraguai",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 5,
   "fase": "grupos",
   "grupo": "B",
   "num": null,
   "data": "2026-06-13",
   "diaSemana": "Sábado",
   "hora": "16h00",
   "iso": "2026-06-13T16:00:00-03:00",
   "t1": "Catar",
   "t2": "Suíça",
   "cidade": "São Francisco",
   "estadio": "Levi's Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 6,
   "fase": "grupos",
   "grupo": "C",
   "num": null,
   "data": "2026-06-13",
   "diaSemana": "Sábado",
   "hora": "19h00",
   "iso": "2026-06-13T19:00:00-03:00",
   "t1": "Brasil",
   "t2": "Marrocos",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": true,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 7,
   "fase": "grupos",
   "grupo": "C",
   "num": null,
   "data": "2026-06-13",
   "diaSemana": "Sábado",
   "hora": "22h00",
   "iso": "2026-06-13T22:00:00-03:00",
   "t1": "Haiti",
   "t2": "Escócia",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 8,
   "fase": "grupos",
   "grupo": "D",
   "num": null,
   "data": "2026-06-14",
   "diaSemana": "Domingo",
   "hora": "01h00",
   "iso": "2026-06-14T01:00:00-03:00",
   "t1": "Austrália",
   "t2": "Turquia",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 9,
   "fase": "grupos",
   "grupo": "E",
   "num": null,
   "data": "2026-06-14",
   "diaSemana": "Domingo",
   "hora": "14h00",
   "iso": "2026-06-14T14:00:00-03:00",
   "t1": "Alemanha",
   "t2": "Curaçao",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 10,
   "fase": "grupos",
   "grupo": "F",
   "num": null,
   "data": "2026-06-14",
   "diaSemana": "Domingo",
   "hora": "17h00",
   "iso": "2026-06-14T17:00:00-03:00",
   "t1": "Holanda",
   "t2": "Japão",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 11,
   "fase": "grupos",
   "grupo": "E",
   "num": null,
   "data": "2026-06-14",
   "diaSemana": "Domingo",
   "hora": "20h00",
   "iso": "2026-06-14T20:00:00-03:00",
   "t1": "Costa do Marfim",
   "t2": "Equador",
   "cidade": "Filadélfia",
   "estadio": "Lincoln Financial Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 12,
   "fase": "grupos",
   "grupo": "F",
   "num": null,
   "data": "2026-06-14",
   "diaSemana": "Domingo",
   "hora": "23h00",
   "iso": "2026-06-14T23:00:00-03:00",
   "t1": "Suécia",
   "t2": "Tunísia",
   "cidade": "Monterrey",
   "estadio": "Estadio BBVA",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 13,
   "fase": "grupos",
   "grupo": "H",
   "num": null,
   "data": "2026-06-15",
   "diaSemana": "Segunda-feira",
   "hora": "13h00",
   "iso": "2026-06-15T13:00:00-03:00",
   "t1": "Espanha",
   "t2": "Cabo Verde",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 14,
   "fase": "grupos",
   "grupo": "G",
   "num": null,
   "data": "2026-06-15",
   "diaSemana": "Segunda-feira",
   "hora": "16h00",
   "iso": "2026-06-15T16:00:00-03:00",
   "t1": "Bélgica",
   "t2": "Egito",
   "cidade": "Seattle",
   "estadio": "Lumen Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 15,
   "fase": "grupos",
   "grupo": "H",
   "num": null,
   "data": "2026-06-15",
   "diaSemana": "Segunda-feira",
   "hora": "19h00",
   "iso": "2026-06-15T19:00:00-03:00",
   "t1": "Arábia Saudita",
   "t2": "Uruguai",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 16,
   "fase": "grupos",
   "grupo": "G",
   "num": null,
   "data": "2026-06-15",
   "diaSemana": "Segunda-feira",
   "hora": "22h00",
   "iso": "2026-06-15T22:00:00-03:00",
   "t1": "Irã",
   "t2": "Nova Zelândia",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 17,
   "fase": "grupos",
   "grupo": "I",
   "num": null,
   "data": "2026-06-16",
   "diaSemana": "Terça-feira",
   "hora": "16h00",
   "iso": "2026-06-16T16:00:00-03:00",
   "t1": "França",
   "t2": "Senegal",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 18,
   "fase": "grupos",
   "grupo": "I",
   "num": null,
   "data": "2026-06-16",
   "diaSemana": "Terça-feira",
   "hora": "19h00",
   "iso": "2026-06-16T19:00:00-03:00",
   "t1": "Iraque",
   "t2": "Noruega",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 19,
   "fase": "grupos",
   "grupo": "J",
   "num": null,
   "data": "2026-06-16",
   "diaSemana": "Terça-feira",
   "hora": "22h00",
   "iso": "2026-06-16T22:00:00-03:00",
   "t1": "Argentina",
   "t2": "Argélia",
   "cidade": "Kansas City",
   "estadio": "GEHA Field at Arrowhead",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 20,
   "fase": "grupos",
   "grupo": "J",
   "num": null,
   "data": "2026-06-17",
   "diaSemana": "Quarta-feira",
   "hora": "01h00",
   "iso": "2026-06-17T01:00:00-03:00",
   "t1": "Áustria",
   "t2": "Jordânia",
   "cidade": "São Francisco",
   "estadio": "Levi's Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 21,
   "fase": "grupos",
   "grupo": "K",
   "num": null,
   "data": "2026-06-17",
   "diaSemana": "Quarta-feira",
   "hora": "14h00",
   "iso": "2026-06-17T14:00:00-03:00",
   "t1": "Portugal",
   "t2": "RD Congo",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 22,
   "fase": "grupos",
   "grupo": "L",
   "num": null,
   "data": "2026-06-17",
   "diaSemana": "Quarta-feira",
   "hora": "17h00",
   "iso": "2026-06-17T17:00:00-03:00",
   "t1": "Inglaterra",
   "t2": "Croácia",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 23,
   "fase": "grupos",
   "grupo": "L",
   "num": null,
   "data": "2026-06-17",
   "diaSemana": "Quarta-feira",
   "hora": "20h00",
   "iso": "2026-06-17T20:00:00-03:00",
   "t1": "Gana",
   "t2": "Panamá",
   "cidade": "Toronto",
   "estadio": "BMO Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 24,
   "fase": "grupos",
   "grupo": "K",
   "num": null,
   "data": "2026-06-17",
   "diaSemana": "Quarta-feira",
   "hora": "23h00",
   "iso": "2026-06-17T23:00:00-03:00",
   "t1": "Uzbequistão",
   "t2": "Colômbia",
   "cidade": "Cidade do México",
   "estadio": "Estádio Azteca (Banorte)",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 25,
   "fase": "grupos",
   "grupo": "A",
   "num": null,
   "data": "2026-06-18",
   "diaSemana": "Quinta-feira",
   "hora": "13h00",
   "iso": "2026-06-18T13:00:00-03:00",
   "t1": "República Tcheca",
   "t2": "África do Sul",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 26,
   "fase": "grupos",
   "grupo": "B",
   "num": null,
   "data": "2026-06-18",
   "diaSemana": "Quinta-feira",
   "hora": "16h00",
   "iso": "2026-06-18T16:00:00-03:00",
   "t1": "Suíça",
   "t2": "Bósnia e Herzegovina",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 27,
   "fase": "grupos",
   "grupo": "B",
   "num": null,
   "data": "2026-06-18",
   "diaSemana": "Quinta-feira",
   "hora": "19h00",
   "iso": "2026-06-18T19:00:00-03:00",
   "t1": "Canadá",
   "t2": "Catar",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 28,
   "fase": "grupos",
   "grupo": "A",
   "num": null,
   "data": "2026-06-18",
   "diaSemana": "Quinta-feira",
   "hora": "22h00",
   "iso": "2026-06-18T22:00:00-03:00",
   "t1": "México",
   "t2": "Coreia do Sul",
   "cidade": "Guadalajara",
   "estadio": "Estadio Akron",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 29,
   "fase": "grupos",
   "grupo": "D",
   "num": null,
   "data": "2026-06-19",
   "diaSemana": "Sexta-feira",
   "hora": "16h00",
   "iso": "2026-06-19T16:00:00-03:00",
   "t1": "Estados Unidos",
   "t2": "Austrália",
   "cidade": "Seattle",
   "estadio": "Lumen Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 30,
   "fase": "grupos",
   "grupo": "C",
   "num": null,
   "data": "2026-06-19",
   "diaSemana": "Sexta-feira",
   "hora": "19h00",
   "iso": "2026-06-19T19:00:00-03:00",
   "t1": "Escócia",
   "t2": "Marrocos",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 31,
   "fase": "grupos",
   "grupo": "C",
   "num": null,
   "data": "2026-06-19",
   "diaSemana": "Sexta-feira",
   "hora": "21h30",
   "iso": "2026-06-19T21:30:00-03:00",
   "t1": "Brasil",
   "t2": "Haiti",
   "cidade": "Filadélfia",
   "estadio": "Lincoln Financial Field",
   "brasil": true,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 32,
   "fase": "grupos",
   "grupo": "D",
   "num": null,
   "data": "2026-06-20",
   "diaSemana": "Sábado",
   "hora": "00h00",
   "iso": "2026-06-20T00:00:00-03:00",
   "t1": "Turquia",
   "t2": "Paraguai",
   "cidade": "São Francisco",
   "estadio": "Levi's Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 33,
   "fase": "grupos",
   "grupo": "F",
   "num": null,
   "data": "2026-06-20",
   "diaSemana": "Sábado",
   "hora": "14h00",
   "iso": "2026-06-20T14:00:00-03:00",
   "t1": "Holanda",
   "t2": "Suécia",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 34,
   "fase": "grupos",
   "grupo": "E",
   "num": null,
   "data": "2026-06-20",
   "diaSemana": "Sábado",
   "hora": "17h00",
   "iso": "2026-06-20T17:00:00-03:00",
   "t1": "Alemanha",
   "t2": "Costa do Marfim",
   "cidade": "Toronto",
   "estadio": "BMO Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 35,
   "fase": "grupos",
   "grupo": "E",
   "num": null,
   "data": "2026-06-20",
   "diaSemana": "Sábado",
   "hora": "21h00",
   "iso": "2026-06-20T21:00:00-03:00",
   "t1": "Equador",
   "t2": "Curaçao",
   "cidade": "Kansas City",
   "estadio": "GEHA Field at Arrowhead",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 36,
   "fase": "grupos",
   "grupo": "F",
   "num": null,
   "data": "2026-06-21",
   "diaSemana": "Domingo",
   "hora": "01h00",
   "iso": "2026-06-21T01:00:00-03:00",
   "t1": "Tunísia",
   "t2": "Japão",
   "cidade": "Monterrey",
   "estadio": "Estadio BBVA",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 37,
   "fase": "grupos",
   "grupo": "H",
   "num": null,
   "data": "2026-06-21",
   "diaSemana": "Domingo",
   "hora": "13h00",
   "iso": "2026-06-21T13:00:00-03:00",
   "t1": "Espanha",
   "t2": "Arábia Saudita",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 38,
   "fase": "grupos",
   "grupo": "G",
   "num": null,
   "data": "2026-06-21",
   "diaSemana": "Domingo",
   "hora": "16h00",
   "iso": "2026-06-21T16:00:00-03:00",
   "t1": "Bélgica",
   "t2": "Irã",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 39,
   "fase": "grupos",
   "grupo": "H",
   "num": null,
   "data": "2026-06-21",
   "diaSemana": "Domingo",
   "hora": "19h00",
   "iso": "2026-06-21T19:00:00-03:00",
   "t1": "Uruguai",
   "t2": "Cabo Verde",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 40,
   "fase": "grupos",
   "grupo": "G",
   "num": null,
   "data": "2026-06-21",
   "diaSemana": "Domingo",
   "hora": "22h00",
   "iso": "2026-06-21T22:00:00-03:00",
   "t1": "Nova Zelândia",
   "t2": "Egito",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 41,
   "fase": "grupos",
   "grupo": "J",
   "num": null,
   "data": "2026-06-22",
   "diaSemana": "Segunda-feira",
   "hora": "14h00",
   "iso": "2026-06-22T14:00:00-03:00",
   "t1": "Argentina",
   "t2": "Áustria",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 42,
   "fase": "grupos",
   "grupo": "I",
   "num": null,
   "data": "2026-06-22",
   "diaSemana": "Segunda-feira",
   "hora": "18h00",
   "iso": "2026-06-22T18:00:00-03:00",
   "t1": "França",
   "t2": "Iraque",
   "cidade": "Filadélfia",
   "estadio": "Lincoln Financial Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 43,
   "fase": "grupos",
   "grupo": "I",
   "num": null,
   "data": "2026-06-22",
   "diaSemana": "Segunda-feira",
   "hora": "21h00",
   "iso": "2026-06-22T21:00:00-03:00",
   "t1": "Noruega",
   "t2": "Senegal",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 44,
   "fase": "grupos",
   "grupo": "J",
   "num": null,
   "data": "2026-06-23",
   "diaSemana": "Terça-feira",
   "hora": "00h00",
   "iso": "2026-06-23T00:00:00-03:00",
   "t1": "Jordânia",
   "t2": "Argélia",
   "cidade": "São Francisco",
   "estadio": "Levi's Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 45,
   "fase": "grupos",
   "grupo": "K",
   "num": null,
   "data": "2026-06-23",
   "diaSemana": "Terça-feira",
   "hora": "14h00",
   "iso": "2026-06-23T14:00:00-03:00",
   "t1": "Portugal",
   "t2": "Uzbequistão",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 46,
   "fase": "grupos",
   "grupo": "L",
   "num": null,
   "data": "2026-06-23",
   "diaSemana": "Terça-feira",
   "hora": "17h00",
   "iso": "2026-06-23T17:00:00-03:00",
   "t1": "Inglaterra",
   "t2": "Gana",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 47,
   "fase": "grupos",
   "grupo": "L",
   "num": null,
   "data": "2026-06-23",
   "diaSemana": "Terça-feira",
   "hora": "20h00",
   "iso": "2026-06-23T20:00:00-03:00",
   "t1": "Panamá",
   "t2": "Croácia",
   "cidade": "Toronto",
   "estadio": "BMO Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 48,
   "fase": "grupos",
   "grupo": "K",
   "num": null,
   "data": "2026-06-23",
   "diaSemana": "Terça-feira",
   "hora": "23h00",
   "iso": "2026-06-23T23:00:00-03:00",
   "t1": "Colômbia",
   "t2": "RD Congo",
   "cidade": "Guadalajara",
   "estadio": "Estadio Akron",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 49,
   "fase": "grupos",
   "grupo": "B",
   "num": null,
   "data": "2026-06-24",
   "diaSemana": "Quarta-feira",
   "hora": "16h00",
   "iso": "2026-06-24T16:00:00-03:00",
   "t1": "Suíça",
   "t2": "Canadá",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 50,
   "fase": "grupos",
   "grupo": "B",
   "num": null,
   "data": "2026-06-24",
   "diaSemana": "Quarta-feira",
   "hora": "16h00",
   "iso": "2026-06-24T16:00:00-03:00",
   "t1": "Bósnia e Herzegovina",
   "t2": "Catar",
   "cidade": "Seattle",
   "estadio": "Lumen Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 51,
   "fase": "grupos",
   "grupo": "C",
   "num": null,
   "data": "2026-06-24",
   "diaSemana": "Quarta-feira",
   "hora": "19h00",
   "iso": "2026-06-24T19:00:00-03:00",
   "t1": "Escócia",
   "t2": "Brasil",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": true,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 52,
   "fase": "grupos",
   "grupo": "C",
   "num": null,
   "data": "2026-06-24",
   "diaSemana": "Quarta-feira",
   "hora": "19h00",
   "iso": "2026-06-24T19:00:00-03:00",
   "t1": "Marrocos",
   "t2": "Haiti",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 53,
   "fase": "grupos",
   "grupo": "A",
   "num": null,
   "data": "2026-06-24",
   "diaSemana": "Quarta-feira",
   "hora": "22h00",
   "iso": "2026-06-24T22:00:00-03:00",
   "t1": "República Tcheca",
   "t2": "México",
   "cidade": "Cidade do México",
   "estadio": "Estádio Azteca (Banorte)",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 54,
   "fase": "grupos",
   "grupo": "A",
   "num": null,
   "data": "2026-06-24",
   "diaSemana": "Quarta-feira",
   "hora": "22h00",
   "iso": "2026-06-24T22:00:00-03:00",
   "t1": "África do Sul",
   "t2": "Coreia do Sul",
   "cidade": "Monterrey",
   "estadio": "Estadio BBVA",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 55,
   "fase": "grupos",
   "grupo": "E",
   "num": null,
   "data": "2026-06-25",
   "diaSemana": "Quinta-feira",
   "hora": "17h00",
   "iso": "2026-06-25T17:00:00-03:00",
   "t1": "Curaçao",
   "t2": "Costa do Marfim",
   "cidade": "Filadélfia",
   "estadio": "Lincoln Financial Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 56,
   "fase": "grupos",
   "grupo": "E",
   "num": null,
   "data": "2026-06-25",
   "diaSemana": "Quinta-feira",
   "hora": "17h00",
   "iso": "2026-06-25T17:00:00-03:00",
   "t1": "Equador",
   "t2": "Alemanha",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 57,
   "fase": "grupos",
   "grupo": "F",
   "num": null,
   "data": "2026-06-25",
   "diaSemana": "Quinta-feira",
   "hora": "20h00",
   "iso": "2026-06-25T20:00:00-03:00",
   "t1": "Japão",
   "t2": "Suécia",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 58,
   "fase": "grupos",
   "grupo": "F",
   "num": null,
   "data": "2026-06-25",
   "diaSemana": "Quinta-feira",
   "hora": "20h00",
   "iso": "2026-06-25T20:00:00-03:00",
   "t1": "Tunísia",
   "t2": "Holanda",
   "cidade": "Kansas City",
   "estadio": "GEHA Field at Arrowhead",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 59,
   "fase": "grupos",
   "grupo": "D",
   "num": null,
   "data": "2026-06-25",
   "diaSemana": "Quinta-feira",
   "hora": "23h00",
   "iso": "2026-06-25T23:00:00-03:00",
   "t1": "Turquia",
   "t2": "Estados Unidos",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 60,
   "fase": "grupos",
   "grupo": "D",
   "num": null,
   "data": "2026-06-25",
   "diaSemana": "Quinta-feira",
   "hora": "23h00",
   "iso": "2026-06-25T23:00:00-03:00",
   "t1": "Paraguai",
   "t2": "Austrália",
   "cidade": "São Francisco",
   "estadio": "Levi's Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 61,
   "fase": "grupos",
   "grupo": "I",
   "num": null,
   "data": "2026-06-26",
   "diaSemana": "Sexta-feira",
   "hora": "16h00",
   "iso": "2026-06-26T16:00:00-03:00",
   "t1": "Noruega",
   "t2": "França",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 62,
   "fase": "grupos",
   "grupo": "I",
   "num": null,
   "data": "2026-06-26",
   "diaSemana": "Sexta-feira",
   "hora": "16h00",
   "iso": "2026-06-26T16:00:00-03:00",
   "t1": "Senegal",
   "t2": "Iraque",
   "cidade": "Toronto",
   "estadio": "BMO Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 63,
   "fase": "grupos",
   "grupo": "H",
   "num": null,
   "data": "2026-06-26",
   "diaSemana": "Sexta-feira",
   "hora": "21h00",
   "iso": "2026-06-26T21:00:00-03:00",
   "t1": "Cabo Verde",
   "t2": "Arábia Saudita",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 64,
   "fase": "grupos",
   "grupo": "H",
   "num": null,
   "data": "2026-06-26",
   "diaSemana": "Sexta-feira",
   "hora": "21h00",
   "iso": "2026-06-26T21:00:00-03:00",
   "t1": "Uruguai",
   "t2": "Espanha",
   "cidade": "Guadalajara",
   "estadio": "Estadio Akron",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 65,
   "fase": "grupos",
   "grupo": "G",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "00h00",
   "iso": "2026-06-27T00:00:00-03:00",
   "t1": "Egito",
   "t2": "Irã",
   "cidade": "Seattle",
   "estadio": "Lumen Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 66,
   "fase": "grupos",
   "grupo": "G",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "00h00",
   "iso": "2026-06-27T00:00:00-03:00",
   "t1": "Nova Zelândia",
   "t2": "Bélgica",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 67,
   "fase": "grupos",
   "grupo": "L",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "18h00",
   "iso": "2026-06-27T18:00:00-03:00",
   "t1": "Panamá",
   "t2": "Inglaterra",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 68,
   "fase": "grupos",
   "grupo": "L",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "18h00",
   "iso": "2026-06-27T18:00:00-03:00",
   "t1": "Croácia",
   "t2": "Gana",
   "cidade": "Filadélfia",
   "estadio": "Lincoln Financial Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 69,
   "fase": "grupos",
   "grupo": "K",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "20h30",
   "iso": "2026-06-27T20:30:00-03:00",
   "t1": "Colômbia",
   "t2": "Portugal",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 70,
   "fase": "grupos",
   "grupo": "K",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "20h30",
   "iso": "2026-06-27T20:30:00-03:00",
   "t1": "RD Congo",
   "t2": "Uzbequistão",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 71,
   "fase": "grupos",
   "grupo": "J",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "23h00",
   "iso": "2026-06-27T23:00:00-03:00",
   "t1": "Argélia",
   "t2": "Áustria",
   "cidade": "Kansas City",
   "estadio": "GEHA Field at Arrowhead",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 72,
   "fase": "grupos",
   "grupo": "J",
   "num": null,
   "data": "2026-06-27",
   "diaSemana": "Sábado",
   "hora": "23h00",
   "iso": "2026-06-27T23:00:00-03:00",
   "t1": "Jordânia",
   "t2": "Argentina",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 73,
   "fase": "fase32",
   "grupo": null,
   "num": 73,
   "data": "2026-06-28",
   "diaSemana": "Domingo",
   "hora": "16h00",
   "iso": "2026-06-28T16:00:00-03:00",
   "t1": "2º do Grupo A",
   "t2": "2º do Grupo B",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 74,
   "fase": "fase32",
   "grupo": null,
   "num": 76,
   "data": "2026-06-29",
   "diaSemana": "Segunda-feira",
   "hora": "14h00",
   "iso": "2026-06-29T14:00:00-03:00",
   "t1": "1º do Grupo C",
   "t2": "2º do Grupo F",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 75,
   "fase": "fase32",
   "grupo": null,
   "num": 74,
   "data": "2026-06-29",
   "diaSemana": "Segunda-feira",
   "hora": "17h30",
   "iso": "2026-06-29T17:30:00-03:00",
   "t1": "1º do Grupo E",
   "t2": "3º colocado (A/B/C/D/F)",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 76,
   "fase": "fase32",
   "grupo": null,
   "num": 75,
   "data": "2026-06-29",
   "diaSemana": "Segunda-feira",
   "hora": "22h00",
   "iso": "2026-06-29T22:00:00-03:00",
   "t1": "1º do Grupo F",
   "t2": "2º do Grupo C",
   "cidade": "Monterrey",
   "estadio": "Estadio BBVA",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 77,
   "fase": "fase32",
   "grupo": null,
   "num": 78,
   "data": "2026-06-30",
   "diaSemana": "Terça-feira",
   "hora": "14h00",
   "iso": "2026-06-30T14:00:00-03:00",
   "t1": "2º do Grupo E",
   "t2": "2º do Grupo I",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 78,
   "fase": "fase32",
   "grupo": null,
   "num": 77,
   "data": "2026-06-30",
   "diaSemana": "Terça-feira",
   "hora": "18h00",
   "iso": "2026-06-30T18:00:00-03:00",
   "t1": "1º do Grupo I",
   "t2": "3º colocado (C/D/F/G/H)",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 79,
   "fase": "fase32",
   "grupo": null,
   "num": 79,
   "data": "2026-06-30",
   "diaSemana": "Terça-feira",
   "hora": "22h00",
   "iso": "2026-06-30T22:00:00-03:00",
   "t1": "1º do Grupo A",
   "t2": "3º colocado (C/E/F/H/I)",
   "cidade": "Cidade do México",
   "estadio": "Estádio Azteca (Banorte)",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 80,
   "fase": "fase32",
   "grupo": null,
   "num": 80,
   "data": "2026-07-01",
   "diaSemana": "Quarta-feira",
   "hora": "13h00",
   "iso": "2026-07-01T13:00:00-03:00",
   "t1": "1º do Grupo L",
   "t2": "3º colocado (E/H/I/J/K)",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 81,
   "fase": "fase32",
   "grupo": null,
   "num": 82,
   "data": "2026-07-01",
   "diaSemana": "Quarta-feira",
   "hora": "17h00",
   "iso": "2026-07-01T17:00:00-03:00",
   "t1": "1º do Grupo G",
   "t2": "3º colocado (A/E/H/I/J)",
   "cidade": "Seattle",
   "estadio": "Lumen Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 82,
   "fase": "fase32",
   "grupo": null,
   "num": 81,
   "data": "2026-07-01",
   "diaSemana": "Quarta-feira",
   "hora": "21h00",
   "iso": "2026-07-01T21:00:00-03:00",
   "t1": "1º do Grupo D",
   "t2": "3º colocado (B/E/F/I/J)",
   "cidade": "São Francisco",
   "estadio": "Levi's Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 83,
   "fase": "fase32",
   "grupo": null,
   "num": 84,
   "data": "2026-07-02",
   "diaSemana": "Quinta-feira",
   "hora": "16h00",
   "iso": "2026-07-02T16:00:00-03:00",
   "t1": "1º do Grupo H",
   "t2": "2º do Grupo J",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 84,
   "fase": "fase32",
   "grupo": null,
   "num": 83,
   "data": "2026-07-02",
   "diaSemana": "Quinta-feira",
   "hora": "20h00",
   "iso": "2026-07-02T20:00:00-03:00",
   "t1": "2º do Grupo K",
   "t2": "2º do Grupo L",
   "cidade": "Toronto",
   "estadio": "BMO Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 85,
   "fase": "fase32",
   "grupo": null,
   "num": 85,
   "data": "2026-07-03",
   "diaSemana": "Sexta-feira",
   "hora": "00h00",
   "iso": "2026-07-03T00:00:00-03:00",
   "t1": "1º do Grupo B",
   "t2": "3º colocado (E/F/G/I/J)",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 86,
   "fase": "fase32",
   "grupo": null,
   "num": 88,
   "data": "2026-07-03",
   "diaSemana": "Sexta-feira",
   "hora": "15h00",
   "iso": "2026-07-03T15:00:00-03:00",
   "t1": "2º do Grupo D",
   "t2": "2º do Grupo G",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 87,
   "fase": "fase32",
   "grupo": null,
   "num": 86,
   "data": "2026-07-03",
   "diaSemana": "Sexta-feira",
   "hora": "19h00",
   "iso": "2026-07-03T19:00:00-03:00",
   "t1": "1º do Grupo J",
   "t2": "2º do Grupo H",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 88,
   "fase": "fase32",
   "grupo": null,
   "num": 87,
   "data": "2026-07-03",
   "diaSemana": "Sexta-feira",
   "hora": "22h30",
   "iso": "2026-07-03T22:30:00-03:00",
   "t1": "1º do Grupo K",
   "t2": "3º colocado (D/E/I/J/L)",
   "cidade": "Kansas City",
   "estadio": "GEHA Field at Arrowhead",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 89,
   "fase": "oitavas",
   "grupo": null,
   "num": 90,
   "data": "2026-07-04",
   "diaSemana": "Sábado",
   "hora": "14h00",
   "iso": "2026-07-04T14:00:00-03:00",
   "t1": "Vencedor do Jogo 73",
   "t2": "Vencedor do Jogo 75",
   "cidade": "Houston",
   "estadio": "NRG Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 90,
   "fase": "oitavas",
   "grupo": null,
   "num": 89,
   "data": "2026-07-04",
   "diaSemana": "Sábado",
   "hora": "18h00",
   "iso": "2026-07-04T18:00:00-03:00",
   "t1": "Vencedor do Jogo 74",
   "t2": "Vencedor do Jogo 77",
   "cidade": "Filadélfia",
   "estadio": "Lincoln Financial Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 91,
   "fase": "oitavas",
   "grupo": null,
   "num": 91,
   "data": "2026-07-05",
   "diaSemana": "Domingo",
   "hora": "17h00",
   "iso": "2026-07-05T17:00:00-03:00",
   "t1": "Vencedor do Jogo 76",
   "t2": "Vencedor do Jogo 78",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 92,
   "fase": "oitavas",
   "grupo": null,
   "num": 92,
   "data": "2026-07-05",
   "diaSemana": "Domingo",
   "hora": "21h00",
   "iso": "2026-07-05T21:00:00-03:00",
   "t1": "Vencedor do Jogo 79",
   "t2": "Vencedor do Jogo 80",
   "cidade": "Cidade do México",
   "estadio": "Estádio Azteca (Banorte)",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 93,
   "fase": "oitavas",
   "grupo": null,
   "num": 93,
   "data": "2026-07-06",
   "diaSemana": "Segunda-feira",
   "hora": "16h00",
   "iso": "2026-07-06T16:00:00-03:00",
   "t1": "Vencedor do Jogo 83",
   "t2": "Vencedor do Jogo 84",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 94,
   "fase": "oitavas",
   "grupo": null,
   "num": 94,
   "data": "2026-07-06",
   "diaSemana": "Segunda-feira",
   "hora": "21h00",
   "iso": "2026-07-06T21:00:00-03:00",
   "t1": "Vencedor do Jogo 81",
   "t2": "Vencedor do Jogo 82",
   "cidade": "Seattle",
   "estadio": "Lumen Field",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 95,
   "fase": "oitavas",
   "grupo": null,
   "num": 95,
   "data": "2026-07-07",
   "diaSemana": "Terça-feira",
   "hora": "13h00",
   "iso": "2026-07-07T13:00:00-03:00",
   "t1": "Vencedor do Jogo 86",
   "t2": "Vencedor do Jogo 88",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 96,
   "fase": "oitavas",
   "grupo": null,
   "num": 96,
   "data": "2026-07-07",
   "diaSemana": "Terça-feira",
   "hora": "17h00",
   "iso": "2026-07-07T17:00:00-03:00",
   "t1": "Vencedor do Jogo 85",
   "t2": "Vencedor do Jogo 87",
   "cidade": "Vancouver",
   "estadio": "BC Place",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 97,
   "fase": "quartas",
   "grupo": null,
   "num": 97,
   "data": "2026-07-09",
   "diaSemana": "Quinta-feira",
   "hora": "17h00",
   "iso": "2026-07-09T17:00:00-03:00",
   "t1": "Vencedor do Jogo 89",
   "t2": "Vencedor do Jogo 90",
   "cidade": "Boston",
   "estadio": "Gillette Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 98,
   "fase": "quartas",
   "grupo": null,
   "num": 98,
   "data": "2026-07-10",
   "diaSemana": "Sexta-feira",
   "hora": "16h00",
   "iso": "2026-07-10T16:00:00-03:00",
   "t1": "Vencedor do Jogo 93",
   "t2": "Vencedor do Jogo 94",
   "cidade": "Los Angeles",
   "estadio": "SoFi Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 99,
   "fase": "quartas",
   "grupo": null,
   "num": 99,
   "data": "2026-07-11",
   "diaSemana": "Sábado",
   "hora": "18h00",
   "iso": "2026-07-11T18:00:00-03:00",
   "t1": "Vencedor do Jogo 91",
   "t2": "Vencedor do Jogo 92",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 100,
   "fase": "quartas",
   "grupo": null,
   "num": 100,
   "data": "2026-07-11",
   "diaSemana": "Sábado",
   "hora": "22h00",
   "iso": "2026-07-11T22:00:00-03:00",
   "t1": "Vencedor do Jogo 95",
   "t2": "Vencedor do Jogo 96",
   "cidade": "Kansas City",
   "estadio": "GEHA Field at Arrowhead",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 101,
   "fase": "semis",
   "grupo": null,
   "num": 101,
   "data": "2026-07-14",
   "diaSemana": "Terça-feira",
   "hora": "16h00",
   "iso": "2026-07-14T16:00:00-03:00",
   "t1": "Vencedor do Jogo 97",
   "t2": "Vencedor do Jogo 98",
   "cidade": "Dallas",
   "estadio": "AT&T Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 102,
   "fase": "semis",
   "grupo": null,
   "num": 102,
   "data": "2026-07-15",
   "diaSemana": "Quarta-feira",
   "hora": "16h00",
   "iso": "2026-07-15T16:00:00-03:00",
   "t1": "Vencedor do Jogo 99",
   "t2": "Vencedor do Jogo 100",
   "cidade": "Atlanta",
   "estadio": "Mercedes-Benz Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 103,
   "fase": "terceiro",
   "grupo": null,
   "num": 103,
   "data": "2026-07-18",
   "diaSemana": "Sábado",
   "hora": "18h00",
   "iso": "2026-07-18T18:00:00-03:00",
   "t1": "Perdedor do Jogo 101",
   "t2": "Perdedor do Jogo 102",
   "cidade": "Miami",
   "estadio": "Hard Rock Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  },
  {
   "id": 104,
   "fase": "final",
   "grupo": null,
   "num": 104,
   "data": "2026-07-19",
   "diaSemana": "Domingo",
   "hora": "16h00",
   "iso": "2026-07-19T16:00:00-03:00",
   "t1": "Vencedor do Jogo 101",
   "t2": "Vencedor do Jogo 102",
   "cidade": "Nova York",
   "estadio": "MetLife Stadium",
   "brasil": false,
   "p1": null,
   "p2": null,
   "fim": false
  }
 ],
 "grupos": [
  {
   "letra": "A",
   "selecoes": [
    "México",
    "África do Sul",
    "Coreia do Sul",
    "República Tcheca"
   ]
  },
  {
   "letra": "B",
   "selecoes": [
    "Canadá",
    "Bósnia e Herzegovina",
    "Catar",
    "Suíça"
   ]
  },
  {
   "letra": "C",
   "selecoes": [
    "Brasil",
    "Marrocos",
    "Haiti",
    "Escócia"
   ]
  },
  {
   "letra": "D",
   "selecoes": [
    "Estados Unidos",
    "Paraguai",
    "Austrália",
    "Turquia"
   ]
  },
  {
   "letra": "E",
   "selecoes": [
    "Alemanha",
    "Curaçao",
    "Costa do Marfim",
    "Equador"
   ]
  },
  {
   "letra": "F",
   "selecoes": [
    "Holanda",
    "Japão",
    "Suécia",
    "Tunísia"
   ]
  },
  {
   "letra": "G",
   "selecoes": [
    "Bélgica",
    "Egito",
    "Irã",
    "Nova Zelândia"
   ]
  },
  {
   "letra": "H",
   "selecoes": [
    "Espanha",
    "Cabo Verde",
    "Arábia Saudita",
    "Uruguai"
   ]
  },
  {
   "letra": "I",
   "selecoes": [
    "França",
    "Senegal",
    "Iraque",
    "Noruega"
   ]
  },
  {
   "letra": "J",
   "selecoes": [
    "Argentina",
    "Argélia",
    "Áustria",
    "Jordânia"
   ]
  },
  {
   "letra": "K",
   "selecoes": [
    "Portugal",
    "RD Congo",
    "Uzbequistão",
    "Colômbia"
   ]
  },
  {
   "letra": "L",
   "selecoes": [
    "Inglaterra",
    "Croácia",
    "Panamá",
    "Gana"
   ]
  }
 ],
 "estadios": [
  {
   "cidade": "Cidade do México",
   "nome": "Estádio Azteca (Banorte)",
   "capacidade": "83.264",
   "pais": "México"
  },
  {
   "cidade": "Guadalajara",
   "nome": "Estadio Akron",
   "capacidade": "48.000",
   "pais": "México"
  },
  {
   "cidade": "Monterrey",
   "nome": "Estadio BBVA",
   "capacidade": "53.500",
   "pais": "México"
  },
  {
   "cidade": "Toronto",
   "nome": "BMO Field",
   "capacidade": "45.000",
   "pais": "Canadá"
  },
  {
   "cidade": "Vancouver",
   "nome": "BC Place",
   "capacidade": "54.500",
   "pais": "Canadá"
  },
  {
   "cidade": "Nova York",
   "nome": "MetLife Stadium",
   "capacidade": "82.500",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Boston",
   "nome": "Gillette Stadium",
   "capacidade": "65.878",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Filadélfia",
   "nome": "Lincoln Financial Field",
   "capacidade": "69.796",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Miami",
   "nome": "Hard Rock Stadium",
   "capacidade": "65.326",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Atlanta",
   "nome": "Mercedes-Benz Stadium",
   "capacidade": "71.000",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Houston",
   "nome": "NRG Stadium",
   "capacidade": "72.220",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Dallas",
   "nome": "AT&T Stadium",
   "capacidade": "80.000",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Kansas City",
   "nome": "GEHA Field at Arrowhead",
   "capacidade": "76.416",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Los Angeles",
   "nome": "SoFi Stadium",
   "capacidade": "70.240",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "São Francisco",
   "nome": "Levi's Stadium",
   "capacidade": "68.500",
   "pais": "Estados Unidos"
  },
  {
   "cidade": "Seattle",
   "nome": "Lumen Field",
   "capacidade": "69.000",
   "pais": "Estados Unidos"
  }
 ],
 "rankingFifa": [
  {
   "pos": "1º",
   "selecao": "Argentina"
  },
  {
   "pos": "2º",
   "selecao": "Espanha"
  },
  {
   "pos": "3º",
   "selecao": "França"
  },
  {
   "pos": "4º",
   "selecao": "Inglaterra"
  },
  {
   "pos": "5º",
   "selecao": "Portugal"
  },
  {
   "pos": "6º",
   "selecao": "Brasil"
  },
  {
   "pos": "7º",
   "selecao": "Marrocos"
  },
  {
   "pos": "8º",
   "selecao": "Holanda (Países Baixos)"
  },
  {
   "pos": "9º",
   "selecao": "Bélgica"
  },
  {
   "pos": "10º",
   "selecao": "Alemanha"
  }
 ],
 "favoritas": [
  {
   "selecao": "Espanha",
   "probabilidade": "15,58%",
   "odds": "5,50",
   "athletic": "1ª"
  },
  {
   "selecao": "França",
   "probabilidade": "12,70%",
   "odds": "6,00",
   "athletic": "3ª"
  },
  {
   "selecao": "Inglaterra",
   "probabilidade": "11,18%",
   "odds": "8,00",
   "athletic": "6ª"
  },
  {
   "selecao": "Argentina",
   "probabilidade": "10,43%",
   "odds": "9,50",
   "athletic": "2ª"
  },
  {
   "selecao": "Portugal",
   "probabilidade": "7,04%",
   "odds": "12,00",
   "athletic": "7ª"
  },
  {
   "selecao": "Brasil",
   "probabilidade": "6,56%",
   "odds": "9,00",
   "athletic": "4ª"
  },
  {
   "selecao": "Holanda",
   "probabilidade": "3,86%",
   "odds": "20,00",
   "athletic": "5ª"
  },
  {
   "selecao": "Marrocos",
   "probabilidade": "1,75%",
   "odds": "65,00",
   "athletic": "11ª"
  }
 ]
};
